import React,{useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{Upload,Activity,Camera,RotateCcw,X,Image as ImageIcon}from'lucide-react';import'./style.css';
type P={x:number,y:number};type View='front'|'side'|'back';
const labels={front:'정면',side:'측면',back:'후면'};const initial:Record<View,Record<string,P>>={front:{ls:{x:38,y:28},rs:{x:62,y:29},lh:{x:43,y:54},rh:{x:57,y:53},lk:{x:44,y:75},rk:{x:56,y:75}},side:{ear:{x:54,y:17},shoulder:{x:49,y:29},hip:{x:50,y:54},knee:{x:51,y:75},ankle:{x:50,y:93}},back:{ls:{x:38,y:28},rs:{x:62,y:29},lh:{x:43,y:54},rh:{x:57,y:53},lk:{x:44,y:75},rk:{x:56,y:75}}};
const angle=(a:P,b:P)=>Math.abs(Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI);
function Guide({view}:{view:View}){return <div className={'guide '+view}><div className="head"/><div className="body"/><div className="arms"/><div className="legs"/><div className="feet"/><div className="axis"/></div>}
function App(){const[view,setView]=useState<View>('front'),[img,setImg]=useState<Record<string,string>>({}),[pts,setPts]=useState(initial),[name,setName]=useState('김회원'),[shoot,setShoot]=useState(false),[stream,setStream]=useState<MediaStream|null>(null);const video=useRef<HTMLVideoElement>(null),drag=useRef<string|null>(null);const p=pts[view];
const metrics=useMemo(()=>view==='side'?[['머리 전방 이동',Math.abs(p.ear.x-p.shoulder.x).toFixed(1)+'%'],['몸통 정렬',Math.abs(p.shoulder.x-p.hip.x).toFixed(1)+'%']]:[['어깨 기울기',angle(p.ls,p.rs).toFixed(1)+'°'],['골반 기울기',angle(p.lh,p.rh).toFixed(1)+'°'],['무릎 높이차',Math.abs(p.lk.y-p.rk.y).toFixed(1)+'%']],[p,view]);
function move(e:React.PointerEvent<HTMLDivElement>){if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect();setPts(q=>({...q,[view]:{...q[view],[drag.current!]:{x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))}}}))}
async function openCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});setStream(s);setShoot(true);setTimeout(()=>{if(video.current)video.current.srcObject=s},50)}catch{alert('카메라 권한을 허용해 주세요.')}}
function closeCamera(){stream?.getTracks().forEach(t=>t.stop());setStream(null);setShoot(false)}
function capture(){if(!video.current)return;const c=document.createElement('canvas');c.width=video.current.videoWidth;c.height=video.current.videoHeight;c.getContext('2d')!.drawImage(video.current,0,0);setImg(q=>({...q,[view]:c.toDataURL('image/jpeg',.92)}));closeCamera()}
return <main><header><div><b>AMAZING</b><span>POSTURE LAB</span></div><em>체형 측정 v0.2</em></header><section className="member"><div className="avatar">{name[0]}</div><div><small>분석 회원</small><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="tag">촬영 · 측정 · 비교</div></section><nav>{(['front','side','back']as View[]).map(v=><button key={v} className={view===v?'on':''} onClick={()=>setView(v)}>{labels[v]}</button>)}</nav><div className="grid"><section className="photo"><div className="stage" onPointerMove={move} onPointerUp={()=>drag.current=null}>{img[view]?<img src={img[view]}/>:<div className="empty"><Guide view={view}/><strong>{labels[view]} 촬영 예시</strong><span>{view==='side'?'카메라를 향해 옆으로 서고 귀·어깨·골반·발목이 보이게':'카메라 정중앙에 서서 머리부터 발끝까지 전신이 보이게'}</span></div>}{img[view]&&Object.entries(p).map(([k,v])=><i key={k} style={{left:v.x+'%',top:v.y+'%'}} onPointerDown={()=>drag.current=k}/>)}</div><div className="actions"><button className="camera" onClick={openCamera}><Camera size={18}/>바로 촬영</button><label><ImageIcon size={18}/>사진 불러오기<input type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f)setImg({...img,[view]:URL.createObjectURL(f)})}}/></label><button className="ghost" onClick={()=>setPts(initial)}><RotateCcw size={16}/>초기화</button></div></section><aside><h2><Activity/>분석 결과</h2><p className="notice">측정점을 실제 관절 위치에 맞추면 수치가 즉시 갱신됩니다.</p>{metrics.map(([a,b])=><div className="metric" key={a}><span>{a}</span><strong>{b}</strong></div>)}<div className="comment"><b>트레이너 코멘트</b><textarea placeholder="회원에게 설명할 내용을 입력하세요."/></div><button className="save">분석 기록 저장</button><small className="medical">※ 운동·자세 관찰을 위한 참고 정보이며 의료 진단이 아닙니다.</small></aside></div>{shoot&&<div className="modal"><div className="cameraBox"><button className="close" onClick={closeCamera}><X/></button><h2>{labels[view]} 사진 촬영</h2><p>흰색 가이드 안에 전신을 맞춰주세요</p><div className="live"><video ref={video} autoPlay playsInline/><Guide view={view}/><div className="line"/></div><div className="tips"><b>촬영 TIP</b><span>카메라 높이: 배꼽~골반 높이</span><span>거리: 머리부터 발끝까지 여유 있게</span><span>자세: 힘을 빼고 평소 서 있는 자세</span></div><button className="shutter" onClick={capture}><span/></button></div></div>}</main>}createRoot(document.getElementById('root')!).render(<App/>);